--- #YAML:1.0
name: Class-XML
version: 0.04
author:
  - Matt S Trout <mstrout@cpan.org>
abstract: Simple XML Abstraction
license: perl
requires:
  Carp: 0.0
  Class::Accessor: 0.19
  Class::Data::Inheritable: 0.02
  Test::More: 0.0
  XML::XPath: 1.0
provides:
  Class::XML:
    file: lib/Class/XML.pm
    version: 0.04
generated_by: Module::Build version 0.25
